include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - prefer_final_fields
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - avoid_web_libraries_in_flutter
    - prefer_is_empty
    - prefer_is_not_empty

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

